name: Autobuild for Docker

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache ccache
        id: cache-ccache
        uses: actions/cache@v3
        with:
          path: ccache
          key: ${{ runner.os }}-ccache
      - name: Build the image
        shell: bash
        run: |
          buildah build --volume $(pwd)/ccache:/root/.cache/ccache -t imagename .